blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: GitHub Expert Services
    url: https://github.com/services#services-contact
    about: Contact GitHub Expert Services
