name: admin-support-cli
author: GitHub Expert Services
description: CLI to promote users as admins in a GitHub organization
inputs:
  action:
    description: Command to invoke as part of the CLI
    required: true
  admin_token:
    description: Token to be used for the promotion workflow
    required: true
    default: ${{ github.token }}
  issue_number:
    description: Promotion request issue number
    required: false
    default: ${{ github.event.issue.number }}
  username:
    description: User that will be promoted
    required: false
    default: ${{ github.actor }}
  target_org:
    description: Organization where the user will be granted elevated access
    required: false
  role:
    description: Role to grant (`admin` or `member`)
    required: false
  duration:
    description: Duration between 1 and 8 hours to grant the permission
    required: false
  ticket:
    description: External system ticket where the request has been reported
    required: false
  description:
    description: Description why this access has been requested and what task(s) will be performed
    required: false
  promotion_date:
    description: Date when the promotion happened
    required: false
  demotion_date:
    description: Date when the demotion happened
    required: false
  run_id:
    description: GitHub Actions workflow run ID
    required: true
    default: ${{ github.run_id }}
outputs:
  output:
    description: Command output
runs:
  using: node20
  main: dist/index.js
