name: admin-support-cli
author: GitHub Expert Services
description: CLI to promote users as admins in a GitHub organization
inputs:
  action:
    description:
      Command to invoke as part of the CLI (`check_auto_demotion`,
      `demotion_report`, `promote_demote`)
    required: true
  admin_token:
    description: Token to be used for the promotion workflow
    required: true
  allowed_orgs:
    description:
      Comma-separated list of allowed organizations (e.g. `org1,org2,org3`).
    required: true
  demotion_date:
    description: Date when the demotion happened
    required: false
  issue_number:
    description: Promotion request issue number
    required: false
    default: ${{ github.event.issue.number }}
  parsed_issue:
    description: Parsed issue JSON
    required: false
  promotion_date:
    description: Date when the promotion happened
    required: false
    default: ${{ github.event.issue.created_at }}
  report_path:
    description: Path where the report will be saved
    required: false
    default: ${{ github.workspace }}/reports
  role:
    description: Role to grant (`admin` or `member`)
    required: false
  username:
    description: User that will be promoted
    required: false
    default: ${{ github.actor }}

  # Not sure if these are needed yet.

  run_id:
    description: GitHub Actions workflow run ID
    required: true
    default: ${{ github.run_id }}

outputs:
  output:
    description: Command output
runs:
  using: node20
  main: dist/index.js
