# Your organization name
org: NAME-OF-ORG

# The name of this repository
repository: NAME-OF-REPOSITORY

# The organizations where this automation can be used
supportedOrgs:
  - NAME-OF-THE-SUPPORTED-ORG

# The path where the reports will be saved
reportPath: reports
